version: "3.9"

volumes:
  meilisearch_local_data:

services:
  meilisearch:
    image: "getmeili/meilisearch:v0.28.1"
    environment:
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
    restart: unless-stopped
    ports:
      - "7700:7700"
    volumes:
      - meilisearch_local_data:/data.ms
